Refactored AppView list fetching
UI-Crafter/UI-Crafter pull request #74
Opened 2024-11-12 21:41 UTC by Nephim

2024-11-12 22:01 UTC, Aagaard00 requested changes
After requested changes -> LGTM

2024-11-12 22:01 UTC, Aagaard00 commented on src/UICrafter.Mobile/Components/Pages/AuthPage.razor
Delete this file if its not used

2024-11-12 22:01 UTC, Aagaard00 commented on src/UICrafter/Components/App.razor
> +        <Routes @rendermode="InteractiveServer" Theme="theme" />
Change back to InteractiveAuto

2024-11-13 14:45 UTC, Gormiee approved these changes
LGTM

2024-11-13 20:14 UTC, merged