3 poc mobilapp
UI-Crafter/UI-Crafter pull request #8
Opened 2024-10-18 07:38 UTC by Gormiee

Look at my code

2024-10-18 08:32 UTC, Aagaard00 commented on src/UICrafter.Client/Pages/UICrafterPage.razor
Hvorfor er der ændringer i UICrafterPage i dit PR

2024-10-18 08:37 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocButtonNoMistakes.razor
> +    </div>
Brug gerne Mud components istedet for <div> n stuff

2024-10-18 08:40 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocButtonNoMistakes.razor
> +    }
GetColor() er flere stedet, flyt den ud i en util fil eller noget måske

2024-10-18 08:41 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocButtonNoMistakes.razor
> +    }
SUS

2024-10-18 08:43 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocButtonNoMistakes.razor
> +    </div>
Use Mud Components

2024-10-18 08:44 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocButtonNoMistakes.razor
> +    private Color GetColor()
Get color ud i util eller noget

2024-10-18 08:44 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocLabel.razor
> +    private Color GetColor()
GetColor() util fil

2024-10-18 08:46 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocTextBox.razor
> +</MudTextField>
Vi snakkede om det der med maxlines vs en mere rigid struktur. Men det kan vi tage senere når vi har data model

2024-10-18 08:47 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocTextBox.razor
> +        if (Model == null)
Måske bare lav parameters "public required" istedet

2024-10-18 08:49 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocTextBox.razor
> +            // Join the values with spaces
Overvej om comments burde slettes

2024-10-18 08:52 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocTextBox.razor
> +            StateHasChanged();
Er manuelt StateHasChanged() kald nødvendig når du ændre i en model som er data bindet til UI component?

2024-10-18 08:53 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocTextBox.razor
> +        StateHasChanged();
Manuelt nødvendig?

2024-10-18 08:54 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocTextBox.razor
> +            // For simplicity, we can serialize it to JSON string
Comments...

2024-10-18 08:54 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocTextBox.razor
> +    private Color GetColor()
Get color er lavet mange steder

2024-10-18 08:55 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocTextBox.razor
> +    // private void UpdateTextBox(Dictionary<string, object> jsonResponse)
Udkommenteret kode skal væk

2024-10-18 08:58 UTC, Aagaard00 commented on src/UICrafter.Core/Components/PocTextBox.razor
> +              Label="@Model.Name"
Slet udkommentert kode

2024-10-18 08:58 UTC, Aagaard00 commented on src/UICrafter.Core/Models/BaseModel.cs
> +
Ændres til fælles model på et tidspunk

2024-10-18 09:00 UTC, Aagaard00 commented on src/UICrafter.Core/Utility/JsonReader.cs
> +	/// <returns>A dictionary containing field names and their corresponding values.</returns>
Summary ud af ingen ting?

2024-10-18 09:03 UTC, Aagaard00 commented on src/UICrafter.Core/Utility/StupidStore.cs
> +
Comments

2024-10-18 09:22 UTC, Aagaard00 commented on src/UICrafter.Mobile/Components/Routes.razor
> +            <NotAuthorized>
Udkommenteret kode

2024-10-18 09:23 UTC, Aagaard00 commented on src/UICrafter.Mobile/MauiProgram.cs
Udkommenteret auth stuff

2024-10-18 09:24 UTC, Aagaard00 commented on src/testlib/Areas/MyFeature/Pages/Page1.cshtml
Garbo file?

2024-10-18 09:24 UTC, Aagaard00 commented on src/testlib/Areas/MyFeature/Pages/Page1.cshtml.cs
Garbo file?

2024-10-18 09:24 UTC, Aagaard00 requested changes
Se mine comments.

2024-10-18 09:42 UTC, Gormiee commented on src/UICrafter.Core/Components/PocTextBox.razor
> +            StateHasChanged();
ja

2024-10-18 09:42 UTC, Gormiee commented on src/UICrafter.Core/Components/PocTextBox.razor
> +        StateHasChanged();
ja

2024-10-22 18:44 UTC, Nephim requested changes
Some of this is not that important other than you should know the stuff. There are quite a few things we need to look at. But maybe we should go through your next PR together and fix the stuff that need fixing and such.

Pretty complex feature you got and good job on the stuff

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter.Client/Pages/UICrafterPage.razor
> +        public virtual string Type { get; } = "";
I prefer string.Empty; instead but its not that important imo

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter.Client/UICrafter.Client.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
You are not supposed to use newtonsoft. Dotnet now has their own json serializer. Look at it here:

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/how-to

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter.Core/Components/PocAPIParamInputField.razor
> +</MudNumericField>
If you want you can end tags on  /> instead of wriring <></> you do <tag/>

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter.Core/Components/PocButtonNoMistakes.razor
> +@inject HttpClient Http
Generally you need to use IHttpClientFactory as you could end up getting socket exhaustion. I am uncertain if Blazor hybrid has the exact same issue as ASP.NET Core. But a asking the chat it said that it has the same issues and you should use IHttpClinetFactory in blazor hybrid as well.

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter.Core/Components/PocButtonNoMistakes.razor
> +    public StupidStore? StupidStore { get; set; }
Bad naming

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter.Core/Components/PocButtonNoMistakes.razor
> +                if (response == null)
This is not how you do response checking. And generally it is bad form to use httpclient directly in component this should be abstracted into a handler or service.

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter.Core/Components/PocTextBox.razor
> +        StateHasChanged();
Det er manuelt nødvendigt fordi det er et sub object/field du ændre på og ikke direkte på en parameter.

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter.Core/UICrafter.Core.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
Not allowed

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter.Core/Utility/ColorOptions.cs
> +		return Model.Color?.ToLower() switch
Dotnet has string compare options where you can set ignore case. So Idk about this toLower() there should be some structure where it just checks but ignores casing

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter.Mobile/UICrafter.Mobile.csproj
> +		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
Bad

2024-10-22 18:44 UTC, Nephim commented on src/UICrafter/UICrafter.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
Bad

2024-11-10 13:26 UTC, closed without merging